apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: node4-test
  namespace: default
spec:
  params:
  - name: url
    value: https://github.com/serverless/examples
  - name: revision
    value: master
  type: git
