# kubectl -n default create secret generic docker-registry --from-file=.dockerconfigjson=/root/.docker/config.json --from-file=config.json=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-git-auth-sa
  namespace: default
secrets:
- name: docker-registry
