apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: knative-node4-runtime-you
spec:
  inputs:
    params:
    - name: IMAGE
      description: The URI of the image to push, including registry host
    - name: DIRECTORY
      description: The subdirectory of the workspace/repo
      default: "."
    - name: HANDLER
      default: "function.handler"
    resources:
    - name: sources
      targetPath: /workspace
      type: git
  steps:
  - name: dockerfile
    image: layershop.dangdang.com/cnlab/kaniko-project/executor:debug-v0.13.0
    command:
    - /busybox/sh
    env:
    - name: DOCKER_CONFIG
      value: "/builder/home/.docker/"
#      value: "/docker-auth"
#    volumeMounts:
#    - mountPath: /docker-auth
#      name: docker-auth
#      readOnly: true
# taskrun中有serviceAccountName配置，会直接把docker认证挂载到/builder/home/.docker/config.json
# 如果更改默认路径/builder/home/.docker，需要在task模版中配置volumeMounts，需要docker secret挂载到容器中（是secret不是sa）否则在push时报权限为授权
    args:
    - -c
    - |
      cd /workspace/workspace/$(inputs.params.DIRECTORY)
      cat <<EOF > Dockerfile
        FROM layershop.dangdang.com/cnlab/triggermesh/knative-lambda-node4
        ENV _HANDLER "$(inputs.params.HANDLER)"

        COPY . .
        RUN npm install
        ENTRYPOINT ["/opt/aws-custom-runtime"]
      EOF
#  - name: debug
#    image: layershop.dangdang.com/cnlab/kaniko-project/executor:debug-v0.13.0
#    command:
#    - /busybox/sh
#    env:
#    - name: DOCKER_CONFIG
#      value: "/builder/home/.docker/"
#    volumeMounts:
#    - mountPath: /docker-auth
#      name: docker-auth
#      readOnly: true
#    args:
#    - -c
#    - |
#      sleep 1h
  - name: export
    image: layershop.dangdang.com/cnlab/kaniko-project/executor:debug-v0.13.0
    args:
    - --dockerfile=Dockerfile
    - --context=/workspace/workspace/$(inputs.params.DIRECTORY)
    - --destination=$(inputs.params.IMAGE)
    # Workaround not to use default config which requires gcloud credentials 
    # to pull base image from public gcr registry 
    # https://groups.google.com/d/msg/kaniko-users/r5yoP_Ejm_c/ExoEXksDBAAJ
    env:
    - name: DOCKER_CONFIG
      value: "/builder/home/.docker/"
#      value: "/docker-auth"
#    volumeMounts:
#    - mountPath: /docker-auth
#      name: docker-auth
#      readOnly: true
#  volumes:
#  - name: docker-auth
#    secret:
#      secretName: docker-registry
