apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pipelineresource-git-nodejs4
  namespace: tekton-pipelines
spec:
  params:
  - name: url
    value: https://github.com/serverless/examples
  - name: revision
    value: master
  type: git
