apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-php-build-push-deployment
  namespace: tekton-pipelines
spec:
  inputs:
    resources:
    - name: git-source
      type: git
    params: 
    - name: pathToContext
      type: string
      default: /workspace/
    - name: pathToDockerFile
      type: string
      default: /workspace/git-source/Dockerfile
      # 项目真正地址/workspace/git-source
    - name: pathToDeployment
      type: string
      default: /workspace/git-source/deployment.yaml
  outputs:
    resources:
    - name: builtImage
      type: image
      targetPath: /workspace/output/builtImage
  steps:
#    - name: check
#      image: layershop.xxxx.com/cnlab/kaniko-project/executor:debug-v0.13.0
#      command:
#        - /busybox/sh
#      args:
#      - -c
#      - |
#        sleep 1h
    - name: build-and-push
      # https://github.com/GoogleContainerTools/kaniko
      image: layershop.xxxx.com/cnlab/kaniko-project/executor:debug-v0.13.0
      env:
        - name: "DOCKER_CONFIG"
          # taskrun中有serviceAccountName配置，会直接把docker认证挂载到/builder/home/.docker/config.json
          # 如果更改默认路径/builder/home/.docker，需要在task模版中配置volumeMounts，需要docker secret挂载到容器中（是secret不是sa）否则在push时报权限为授权
          value: "/builder/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(inputs.params.pathToDockerFile)
        - --destination=$(outputs.resources.builtImage.url)
        - --context=$(inputs.params.pathToContext)
    - name: run-kubectl
      #image: lachlanevenson/k8s-kubectl
      image: layershop.xxxx.com/cnlab/k8s-kubectl:v1.14.8
      command: ['kubectl']
      args:
      - 'apply'
      - '-f'
      - '$(inputs.params.pathToDeployment)'
      volumeMounts:
        - name: kubernetes-config
          mountPath: /root/.kube
  volumes:
    - name: kubernetes-config
      configMap:
        name: k8s-config
        items:
          - key: config
            path: config
